### ISSUE TITLE
JavaScript var declarations?

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/conventions#30]
The question that arose: should we allow variable definitions in the format of

```javascript
var something = '',
  somethingElse  = null,
  andYetAnotherCommaFollower = null;
```

or should we keep to:

```js
var something = '';
var somethingElse = null;
var andYetAnotherCommaFollower = null;
```

To me repetitive var declarations are more readable and I know large part of the community actually goes with it. In our current convention that we adopted, there's no coverage on this particular aspect.

@davidyezsetz @GeorgMeyer23 @beroes, ideas/feedback?

**Comment by GeorgMeyer23** [comment]
for me these 2 styles are fine:

var something, somethingElse, andYetAnotherFollower;

or with value:

var something = ‘’;
var somethingElse = null;
var andYetAnother = null;

Georg Meyer
____________________
Entwicklung
Interactive Pioneers GmbH

T   +49 241 91880 50
E   gm@interactive-pioneers.de<mailto:gm@interactive-pioneers.de>
W http://www.interactive-pioneers.de
S   Xing | LinkedIn | Facebook | Twitter | G+

Alle Neuigkeiten der Pioniere im Blog: http://blog.interactive-pioneers.de
Geschäftsführung: Carlo Matic, Amtsgericht Aachen – HRB 8683, Ust-IdNr.: DE220959918

On 21 Apr 2015, at 17:31, Ain Tohvri <notifications@github.com<mailto:notifications@github.com>> wrote:


The question that arose: should we allow variable definitions in the format of

var something = "",
  somethingElse  = null,
  andYetAnotherCommaFollower = null;

or should we keep to:

var something = "";
var somethingElse = "";
var andYetAnotherCommaFollower = null;

To me repetitive var declarations are more readable and I know large part of the community actually goes with it. In our current convention that we adopted, there's no coverage on this particular aspect.

@davidyezsetz<https://github.com/davidyezsetz> @GeorgMeyer23<https://github.com/GeorgMeyer23> @beroes<https://github.com/beroes>, ideas/feedback?

**Comment by davidyezsetz** [comment]
var davy  = '',
      jones = '';
makes sense when you have tab set to 4 spaces because it matches up. Since we don't I would stick to
var giant  = '';
var squid = '';
Also for blocks of vars I would equalise the "=" placement.  (Sublime text has e.g. http://wbond.net/sublime_packages/alignment and vim has https://github.com/godlygeek/tabular)

**Comment by ain** [comment]
We can also keep this one optional as long as all of it is readable. I for
myself have gone for a list of separate var
declarations without formatting. Tabulation looks nice, but also needs
maintenancenwhenever changed in order to not look shit all of the sudden.

-- 
Sent from Gmail Mobile

**Comment by davidyezsetz** [comment]
yup. Alignment is optional, but usually not a lot of work

**Comment by ain** [comment]
So could we conclude with:

- Repetitive var declarations are allowed with tabulation recommended for readability
- If defined in comma-separated list, tabulation has to be applied for readability

**Comment by davidyezsetz** [comment]
Yup
