### ISSUE TITLE
Separate Jekyll theme

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/conventions#48]
Suggestion to move the theme to its own repository with an aim to publish FOSS-licenced IP Jekyll theme. For a good promo :)

Posting it as question for discussion at this point. Hopefully converted to enhancement ;)

**Comment by davidyezsetz** [comment]
Not sure it's worth it, because it's not really theme. I copy pasted the styles from our website and just added modifications on top

**Comment by ain** [comment]
With the code snippet improvements/highlighting you could easily transfer it to one I think. 

Nevertheless, give it a thought and evaluate. If too much work, then of course not worth it.

**Comment by davidyezsetz** [comment]
It would be an IP-specific theme though

**Comment by ain** [comment]
Concluding that there is no community value. Closing.
