### ISSUE TITLE
Dockerise

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/conventions#56]
Create a Docker container with all of it incl. pre-cached dependencies and host it on Docker Hub so all can use to develop the conventions site directly.

**Comment by davidyezsetz** [comment]
Do you think this is worth the effort? The dependencies are only ruby (which everyone has) and jekyll

**Comment by ain** [comment]
You're right. It'd only make sense if we're going Docker in full so it replaces MacPorts/Brew in large parts.

**Comment by davidyezsetz** [comment]
Yup. Closing this one. Re-open if you disagree
