### ISSUE TITLE
Private/public members in closure

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/conventions#64]
Document recommendation of private and public members inside JavaScript closure.

**Comment by davleh** [comment]
Is still necessary? I do not think so. What do you think? If you agree, I would vote for closing this ticket.

**Comment by GeorgMeyer23** [comment]
no need to except you'r exporting a structure like https://github.com/interactive-pioneers/iptools-utils/blob/master/src/iptools-utils.js
