### ISSUE TITLE
Rename google.json to .jscsrc?

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/conventions#65]
I'd suggest to rename JSCS configuration file from `google.json` to `.jscsrc`. That appears to be the default reference for Syntastic in Vim. Should be the same default for Sublime?

Any objections @GeorgMeyer23 @davidyezsetz?

**Comment by davidyezsetz** [comment]
not really. I just went with the original file name

**Comment by ain** [comment]
@GeorgMeyer23, opinion?

**Comment by davidyezsetz** [comment]
Followed up in #67
