### ISSUE TITLE
Preceding semicolon to closure

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/conventions#75]
Bringing it up as a question. By @GeorgMeyer23's initiative we're using 
```js
;
(function($, window, document) { 
```
but this throws up as an error on linting by JSHint. 

My stand on this is mixed as well. I haven't had concatenation problems with libraries when going without it. 

@GeorgMeyer23 @davidyezsetz @beroes opinions?

**Comment by davidyezsetz** [comment]
This only makes sense if you don't know what you're concatenating. If you check all the scripts you use you will not run into problems with unclosed statements. So in our case I don't recommend it

**Comment by GeorgMeyer23** [comment]
We can skip it, since we know what we're doing and only we're only working with high quality tested third party libs.
