### ISSUE TITLE
Forbid excess whitespace

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/conventions#82]
The topic @GeorgMeyer23 raised today: excess whitespace:

 ![whitespace](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/121231/892800/gVHeqtAu2pNVNiQ/upload.png)

Most tools allow automatic removal of such whitespaces (and newlines) and I think we should commit this into our conventions because it avoids version control diff clutter.

Opinions @davidyezsetz @beroes ?

**Comment by davidyezsetz** [comment]
Fully agree. I have vim cough up on whitespace and make sure to always remove it before I commit

**Comment by davleh** [comment]
Whitespace already part of scss and sass linting, thus closing this issue.
