### ISSUE TITLE
SCSS lint - 3 blocks: positioning, box-model, other

### ISSUE THREAD

**Issue by davleh** [interactive-pioneers/conventions#83]
I think we should update our scss lint configuration. According to the conventions we should have three blocks with declarations, first a positioning block, followed by a box-model block and then a third block having any other declarations. This third block should be ordered alphabetically.
With the current configuration we get more blocks.

@ain, @GeorgMeyer23, @beroes - What do you think?

**Comment by ain** [comment]
Are the blocks generally that long? If not, I'd call for not overdoing it. Individual programmer freedom is also cool :D

**Comment by davleh** [comment]
The cool thing about having a lot of properties in the list is, that we can use tools like CssComb for automatically sorting the properties / blocks while coding as sublime text plugin or as a grunt task.

**Comment by GeorgMeyer23** [comment]
I like the idea of having always the same order, defined by conventions. Easy to read, easy to adapt...

**Comment by davleh** [comment]
Closing this issue, as this is outdated.
