### ISSUE TITLE
get rid of redcarpet since github stops support on May 1st.

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/conventions#85]
The page build completed successfully, but returned the following warning:

You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

For information on troubleshooting Jekyll see:

 https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

**Comment by ain** [comment]
Yup. Got to do it.

**Comment by davleh** [comment]
Done.
