### ISSUE TITLE
Set jshint option 'latedef' to 'nofunc'

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/conventions#86]
docs: http://jshint.com/docs/options/#latedef

Setting option `latedef` to `nofunc` will allow to use functions that are defined later in file context.
For example our standard `addEventListeners` may be called before it is defined in the file context.

Variable declaration order will not ne affected.

@ain @beroes @davleh what do you guys think?

**Comment by ain** [comment]
We haven't had problems with `latedef`as it is and I'm always for stricter conventions. It trains one's code to be less error-prone. 

I think it's a good check in terms of missing a method. I've had PRs where listeners have been left out by mistake.

**Comment by beroes** [comment]
I think we have to be more strict and avoid violating the good practices.

**Comment by ain** [comment]
To be fair, good discussion. I actually checked into hoisting.

**Comment by davleh** [comment]
I agree with @GeorgMeyer23 that defining helper methods at the bottom of the code should be allowed. I ran into trouble multiple times: For example when defining variables at the top that should hold the output of a function that is defined later in code. I had to have a mix of function definitions and variable definitions at the top then which made the code less readable. So I would vote for Georgs call.

**Comment by ain** [comment]
Static helper methods should always make it into a different file, e.g. `utils` with Array, String or Object prototypes. Everything else should be within the definition of the class as a static, public or private method. Scope is important.

**Comment by GeorgMeyer23** [comment]
You're right @ain we need a basic utils set for repetitive functions like `selectorFromClass` or `getNamespacedEvents` and so on...

I'd call for a basic `iptools-jquery-utils` and integrate them as dependency in advanced `iptools-jquery-*`.

This solution make this question obsolete / redundant.

**Comment by ain** [comment]
Absolutely. That sounds like a proper modular way of doing it.

**Comment by ain** [comment]
Resolving topic. 

All utilities should go into [iptools-jquery-utils](https://github.com/interactive-pioneers/iptools-jquery-utils).
