### ISSUE TITLE
SCSS lint configuration should not define paths

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/conventions#88]
I'm calling to remove (or comment out) https://github.com/interactive-pioneers/conventions/blob/gh-pages/files/.scss-lint.yml#L1-L5 as this is highly project-dependent. Furthermore, tools like `grunt-scss-lint` already deal with the SCSS file targeting.

**Comment by ain** [comment]
Cc @GeorgMeyer23 @davleh @beroes

**Comment by GeorgMeyer23** [comment]
:+1: I'd call for comment them out, to show that the option is there, even if not used or configured via gulp/grunt.

**Comment by davleh** [comment]
Already done.
